spring.application.name=demo

# ===============================
# MYSQL DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/prod_ready_features?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Mayank@123

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9000

employeeService.base.url=http://localhost:8080

#logging configuration
logging.level.com.Auditing_Tutorial.demo.client= DEBUG

logging.level.com.Auditing_Tutorial.demo.config= INFO

logging.level.root= INFO

logging.pattern.console=%d{dd-MM-yyyy hh:mm:ss} {%level} [%c ] --- %m%n

logging.file.name=application.log
logging.config=classpath:logback-spring.xml

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

info.app.name=mayank
info.app.rollno=22335
info.app.age=22

management.endpoint.env.show-values=always
# management.endpoints.web.base-path=/management  [ used to change the url name to management]

